### ISSUE TITLE
Button Component

### ISSUE THREAD

**Issue by shinzui** [shinzui/react-semantic-ui-kit#1]
[Button docs @Semantic UI](http://semantic-ui.com/elements/button.html)

### Types
- [x] Basic button
- [x]  Simple button
- [x] Emphasis buttons
- [x]  Animated button
- [x] Labeled button
- [x] Icon button
- [x] Labeled icon button
- [x] Inverted
- [x] Button group

### Content

- [x] Conditionals

### States

- [x] Active
- [x] Disabled
- [x] Loading 

### Variations
- [x] Social
- [x] Size 
- [x] Floated 
- [x] Colored
- [x] Compact 
- [x] Toggle 
- [x] Positive 
- [x] Negative 
- [x] Fluid
- [x] Circular
- [x] Vertically attached 
- [x] Horizontally attached 

### Group variations
- [x] Vertical buttons
- [x] Icon buttons 
- [x] Labeled icon buttons 
- [x] Mixed group 
- [x] Equal width
- [x] Colored buttons 
- [x] Basic buttons
- [x] Group sizes

**Comment by jlukic** [comment]
:+1: great work

**Comment by shinzui** [comment]
@jlukic Thank you and thanks for all the work you've done on Semantic UI, it's a great project.
